services:
  hono-template:
    image: hono-template
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    env_file:
      - path: ./.env
        required: true
