services:
  hono-template:
    image: hono-template
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./.env
        required: true
    ports:
      - "${PORT}:${PORT}"
